pipeline {
  agent any
  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t manikanta-test-java .'
      }
    }
    stage('Run Docker Image') {
      steps {
        sh 'docker run manikanta-test-java'
      }
    }
  }
}
