pipeline {
  agent any
  stages {
    stage('git fetch') {
      steps {
        sh 'https://github.com/manikanta513/Jenkins-Zero-To-Hero.git'
      }
    }
    stage('Build Docker Image') {
      steps {
        dir('multi-stage-multi-agent') {
          sh 'docker build -t manikanta-test-java .'
          sh 'docker run manikanta-test-java'
        }
      }
    }
  }
}
